networks:
  app-network:
    driver: bridge

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network
  grpc-server:
    image: openjdk:21-jdk-slim
    container_name: grpc-server
    ports:
      - "8080:8080"
      - "9091:9090" # gRPC port
    volumes:
      - .:/app
      - .mvn:/app/.mvn
    working_dir: /app
    command: ["./mvnw", "spring-boot:run"]
    environment:
      - SPRING_PROFILES_ACTIVE=default
    networks:
      - app-network
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "30303:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - app-network

volumes:
  grafana-storage: